---
permalink: /:year/:month/:title
maruku:
  png_dir: images/latex
  png_url: /images/latex
  use_tex: false
  use_divs: false
lsi: false
destination: ./_site
markdown: maruku
pygments: true
pretty_style: html_extension
auto: true
server_port: 4000
url: http://mini.local/mblog/_site
baseurl: http://mini.local/mblog/_site/
